### ISSUE TITLE
permission dined

### ISSUE THREAD

**Issue by JiyueWang** [kkoutini/cpjku_dcase19#2]
I know this may be a stupid question.Anyone?

CUDA_VISIBLE_DEVICES=0 python exp_cp_resnet.py
The experiment outputs will be found at:  outdir/cp_resnet/exp_Mar04_12.23.50
The experiment tesnorboard can be accessed: tensorboard --logdir   runsdir/cp_resnet/exp_Mar04_12.23.50
Rho value :  5
Use Mix-up :  1
For this Rho, the maximium RF is:  81
0.0
Traceback (most recent call last):
  File "exp_cp_resnet.py", line 77, in <module>
    trainer = Trainer(default_conf)
  File "/data/wjyeasy/cpjku-master/trainer.py", line 64, in __init__
    os.makedirs(config.out_dir)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'outdir/cp_resnet/exp_Mar04_12.23.50'

**Comment by JiyueWang** [comment]
I delate the rundir and rerun, then the issue is gone. Now is the new issue:

.../cpjku-master$ CUDA_VISIBLE_DEVICES=0 python exp_cp_resnet.py
The experiment outputs will be found at:  outdir/cp_resnet/exp_Mar04_15.44.10
The experiment tesnorboard can be accessed: tensorboard --logdir   runsdir/cp_resnet/exp_Mar04_15.44.10
Rho value :  5
Use Mix-up :  1
For this Rho, the maximium RF is:  81
0.0
I: for detailed run info use 
 tail -f outdir/cp_resnet/exp_Mar04_15.44.10/info.log
I: tensorboard run path: runsdir/cp_resnet/exp_Mar04_15.44.10
I: To monitor this experiment use:
 tensorboard --logdir runsdir/cp_resnet/exp_Mar04_15.44.10
Network(
  (in_c): Sequential(
    (0): Conv2d(2, 128, kernel_size=(5, 5), stride=(2, 2), padding=(1, 1), bias=False)
    (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
  )
  (stage1): Sequential(
    (block1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (maxpool1_0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (block2): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (maxpool2_1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (block3): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (block4): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(128, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (maxpool4_2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (stage2): Sequential(
    (block1): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential(
        (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (block2): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (block3): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (block4): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
  )
  (stage3): Sequential(
    (block1): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential(
        (conv): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (block2): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (block3): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
    (block4): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (shortcut): Sequential()
    )
  )
  (feed_forward): Sequential(
    (0): Conv2d(512, 10, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): AdaptiveAvgPool2d(output_size=(1, 1))
  )
)
I: 

Trainable model parameters 3566612, non-trainable 0 


optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: [0.9, 0.999]
    eps: 1e-08
    lr: 0.0001
    weight_decay: 0
)
normalized test!
loading dataset from 'd19t1'
normalizing dataset
attempting to load x from cache at datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt...
Invalid cache datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt , recomputing
cal_mean 
Traceback (most recent call last):
  File "/data/wjyeasy/cpjku-master/datasets.py", line 441, in __init__
    self.obj = torch.load(xpath)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp_cp_resnet.py", line 77, in <module>
    trainer = Trainer(default_conf)
  File "/data/wjyeasy/cpjku-master/trainer.py", line 176, in __init__
    self.init_loaders()
  File "/data/wjyeasy/cpjku-master/trainer.py", line 196, in init_loaders
    ds = self.dataset_manager.get_dataset(dataset_config)
  File "/data/wjyeasy/cpjku-master/datasets.py", line 68, in get_dataset
    return getattr(self, config.dataset.split(".")[1])()
  File "/data/wjyeasy/cpjku-master/datasets.py", line 167, in get_test_set
    fill_norms(name, fold, train_files_csv, audio_processor, self.df_get_train_set())
  File "/data/wjyeasy/cpjku-master/datasets.py", line 671, in fill_norms
    "tr_mean_{}_f{}_ap{}".format(h6(train_files_csv), fold, audio_processor)).get()
  File "/data/wjyeasy/cpjku-master/datasets.py", line 451, in __init__
    self.obj = get_obj_func()
  File "/data/wjyeasy/cpjku-master/datasets.py", line 502, in cal_mean
    for i, (x, _, _) in enumerate(torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=False, num_workers=8)):
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
librosa.util.exceptions.ParameterError: Caught ParameterError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/wjyeasy/cpjku-master/datasets.py", line 441, in __init__
    self.obj = torch.load(xpath)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cached_datasets/d19t1/tr_mean_452f8f_f1_apd18_stereo_obj.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/wjyeasy/cpjku-master/datasets.py", line 297, in __getitem__
    return torch.load(cpath)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/cached_datasets/d19t1/files_cache/_ap_d18_stereo/0.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/wjyeasy/cpjku-master/datasets.py", line 373, in __getitem__
    return self.dataset[self.available_indexes[index]]
  File "/data/wjyeasy/cpjku-master/datasets.py", line 299, in __getitem__
    tup = self.get_dataset_func()[index]
  File "/data/wjyeasy/cpjku-master/datasets.py", line 396, in __getitem__
    x = self.preprocessor(self.base_dir + self.files[index])
  File "/data/wjyeasy/cpjku-master/audioprocessors.py", line 86, in processor_d18_stereo
    pad_mode='reflect')
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/data/wjyeasy/anaconda3/envs/cpjku/lib/python3.6/site-packages/librosa/util/utils.py", line 278, in valid_audio
    raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.

**Comment by JunenuJ** [comment]
I have a smililar problem， did you  solve this problem?

**Comment by JiyueWang** [comment]
Yes, do as the lase error said.
Add the following line after line84 of audioprocessors.py
y=np.asfortranarray(y)

**Comment by JiyueWang** [comment]
have you tried on dcase 2010 task1a, the feature extraction is extremely slow.

**Comment by JunenuJ** [comment]
I have not tried to run this code with case 2020 task1a，but I will try this method.

**Comment by JiyueWang** [comment]
Need to set mono=True in line 13 of audioprocessors.py.

**Comment by JunenuJ** [comment]
Wow, thank you so much，hhh。

**Comment by JunenuJ** [comment]
Hi，I have something which I do not understand about features. When I run this code , I will achieve *.pt files . I think  this files stored features, but I am not sure。Meanwhile，the number of *.pt is 14384 not 14400，do you have this problem?  thanks
