### ISSUE TITLE
Pretrained Model Sub1 test accuray not in accordance with that in the technical report

### ISSUE THREAD

**Issue by sailyifan** [kkoutini/cpjku_dcase19#6]
Anyone tried to get test accuracy result using script eval_pretrained.ipynb? I made a test on pretrained model sub1, but got test accuray 28%, while the restult in technical report was ~95%, a huge difference. 

Any suggestions?

**Comment by kkoutini** [comment]
Hi, this result sounds like random predictions. can you confirm that the last cell in this [notebook ](https://github.com/kkoutini/cpjku_dcase20/blob/master/eval_pretrained.ipynb)
outputs: `"matching tensor(8640) out of  8640"`

**Comment by sailyifan** [comment]
Thanks for your replies. I found that I rasied the issue in the wrong resp, should raised in dcase 2020. I will reopen the issue in the correct resp.
